// Mock data for integrations

import { Connector, ConnectorCategory, CategoryInfo } from '@/types/integrations';

export const mockConnectors: Connector[] = [
  // AI Models
  {
    id: 'openai',
    name: 'OpenAI',
    description: 'Connect GPT-4, GPT-3.5, and other OpenAI models for advanced AI capabilities.',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/0/04/ChatGPT_logo.svg',
    category: 'ai_models',
    status: 'connected',
    lastSync: new Date(Date.now() - 1000 * 60 * 5),
    version: '1.0.0',
    tags: ['AI', 'LLM', 'GPT'],
    authType: 'api_key',
    configFields: [
      { key: 'api_key', label: 'API Key', type: 'password', required: true, placeholder: 'sk-...' },
      { key: 'organization', label: 'Organization ID', type: 'text', required: false, placeholder: 'org-...' },
    ],
    actions: ['Generate Text', 'Analyze Sentiment', 'Summarize', 'Translate'],
    tools: ['text_generation', 'chat_completion', 'embeddings'],
    resources: ['Models', 'Fine-tunes', 'Assistants'],
    rateLimits: { requests: 500, period: 'minute' },
  },
  {
    id: 'anthropic',
    name: 'Anthropic Claude',
    description: 'Access Claude models for safe, helpful, and honest AI interactions.',
    logo: 'https://avatars.githubusercontent.com/u/113150603?s=200&v=4',
    category: 'ai_models',
    status: 'available',
    version: '2.1.0',
    tags: ['AI', 'LLM', 'Claude'],
    authType: 'api_key',
    configFields: [
      { key: 'api_key', label: 'API Key', type: 'password', required: true, placeholder: 'sk-ant-...' },
    ],
    actions: ['Generate Text', 'Code Generation', 'Analysis'],
    tools: ['claude_completion', 'vision', 'tools'],
    resources: ['Models', 'Prompts'],
    rateLimits: { requests: 100, period: 'minute' },
  },
  {
    id: 'nvidia-nim',
    name: 'NVIDIA NIM',
    description: 'Deploy Nemotron, Mistral, and other NVIDIA NIM models for enterprise AI.',
    logo: 'https://cdn.worldvectorlogo.com/logos/nvidia.svg',
    category: 'ai_models',
    status: 'connected',
    lastSync: new Date(Date.now() - 1000 * 60 * 2),
    version: '3.2.0',
    tags: ['AI', 'Enterprise', 'NIM'],
    authType: 'api_key',
    configFields: [
      { key: 'api_key', label: 'API Key', type: 'password', required: true, placeholder: 'nvapi-...' },
      { key: 'endpoint', label: 'Endpoint URL', type: 'text', required: false, placeholder: 'https://integrate.api.nvidia.com/...' },
    ],
    actions: ['Generate Text', 'Embeddings', 'Vision'],
    tools: ['nemotron', 'mistral', 'glm', 'kimik'],
    resources: ['Models', 'Endpoints'],
    rateLimits: { requests: 1000, period: 'minute' },
  },
  {
    id: 'groq',
    name: 'Groq',
    description: 'Ultra-fast inference with Groq LPU for real-time AI applications.',
    logo: 'https://groq.com/wp-content/uploads/2024/03/groq-logo.svg',
    category: 'ai_models',
    status: 'available',
    version: '1.5.0',
    tags: ['AI', 'Fast', 'LLM'],
    authType: 'api_key',
    configFields: [
      { key: 'api_key', label: 'API Key', type: 'password', required: true, placeholder: 'gsk_...' },
    ],
    actions: ['Generate Text', 'Chat Completion'],
    tools: ['llama', 'mixtral', 'gemma'],
    resources: ['Models', 'Inference'],
    rateLimits: { requests: 10000, period: 'minute' },
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    description: 'Access DeepSeek models for coding and reasoning tasks.',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/a/a4/DeepSeek_logo.svg',
    category: 'ai_models',
    status: 'needs_setup',
    version: '1.0.0',
    tags: ['AI', 'Coding', 'Reasoning'],
    authType: 'api_key',
    configFields: [
      { key: 'api_key', label: 'API Key', type: 'password', required: true, placeholder: 'sk-...' },
    ],
    actions: ['Generate Text', 'Code Generation'],
    tools: ['deepseek-chat', 'deepseek-coder'],
    resources: ['Models'],
    rateLimits: { requests: 200, period: 'minute' },
  },

  // MCP Servers
  {
    id: 'filesystem-mcp',
    name: 'Filesystem MCP',
    description: 'Access and manipulate local filesystem through MCP protocol.',
    logo: 'https://cdn-icons-png.flaticon.com/512/716/716784.png',
    category: 'mcp_servers',
    status: 'connected',
    lastSync: new Date(Date.now() - 1000 * 60 * 30),
    version: '1.2.0',
    tags: ['MCP', 'Filesystem', 'Tools'],
    authType: 'custom',
    configFields: [
      { key: 'allowed_paths', label: 'Allowed Paths', type: 'text', required: true, placeholder: '/home/user/docs' },
      { key: 'readonly', label: 'Read Only Mode', type: 'toggle', required: false },
    ],
    actions: ['Read File', 'Write File', 'List Directory', 'Create Directory'],
    tools: ['read', 'write', 'list', 'mkdir', 'stat'],
    resources: ['Files', 'Directories'],
    rateLimits: { requests: 1000, period: 'minute' },
  },
  {
    id: 'github-mcp',
    name: 'GitHub MCP',
    description: 'Integrate with GitHub for repository management and automation.',
    logo: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png',
    category: 'mcp_servers',
    status: 'available',
    version: '2.0.0',
    tags: ['MCP', 'GitHub', 'DevOps'],
    authType: 'oauth',
    configFields: [
      { key: 'github_token', label: 'GitHub Token', type: 'password', required: true },
    ],
    actions: ['List Repos', 'Create Issue', 'PR Review', 'Code Search'],
    tools: ['repos', 'issues', 'pulls', 'actions'],
    resources: ['Repositories', 'Organizations'],
    rateLimits: { requests: 5000, period: 'hour' },
  },
  {
    id: 'slack-mcp',
    name: 'Slack MCP',
    description: 'Send messages and manage Slack workspace interactions.',
    logo: 'https://a.slack-edge.com/80588/marketing/img/icons/icon_slack_hash_colored.png',
    category: 'mcp_servers',
    status: 'available',
    version: '1.5.0',
    tags: ['MCP', 'Slack', 'Communication'],
    authType: 'oauth',
    configFields: [
      { key: 'bot_token', label: 'Bot Token', type: 'password', required: true },
      { key: 'default_channel', label: 'Default Channel', type: 'text', required: false },
    ],
    actions: ['Send Message', 'List Channels', 'Search Messages'],
    tools: ['chat.postMessage', 'conversations.list', 'search.messages'],
    resources: ['Channels', 'Users', 'Messages'],
    rateLimits: { requests: 100, period: 'minute' },
  },

  // Databases
  {
    id: 'supabase',
    name: 'Supabase',
    description: 'PostgreSQL database with real-time subscriptions and auth.',
    logo: 'https://supabase.com/brand-assets/supabase-logo-icon.png',
    category: 'databases',
    status: 'connected',
    lastSync: new Date(Date.now() - 1000 * 60 * 1),
    version: '2.0.0',
    tags: ['Database', 'PostgreSQL', 'Real-time'],
    authType: 'api_key',
    configFields: [
      { key: 'url', label: 'Project URL', type: 'text', required: true, placeholder: 'https://xxx.supabase.co' },
      { key: 'anon_key', label: 'Anon Key', type: 'password', required: true },
      { key: 'service_key', label: 'Service Key', type: 'password', required: false },
    ],
    actions: ['Query', 'Insert', 'Update', 'Delete', 'Subscribe'],
    tools: ['pg_query', 'realtime', 'storage', 'auth'],
    resources: ['Tables', 'Functions', 'Storage'],
    rateLimits: { requests: 2000, period: 'minute' },
  },
  {
    id: 'pinecone',
    name: 'Pinecone',
    description: 'Managed vector database for AI applications and semantic search.',
    logo: 'https://www.pinecone.io/icons/pinecone-logomark.svg',
    category: 'databases',
    status: 'available',
    version: '1.8.0',
    tags: ['Database', 'Vector', 'AI'],
    authType: 'api_key',
    configFields: [
      { key: 'api_key', label: 'API Key', type: 'password', required: true },
      { key: 'environment', label: 'Environment', type: 'select', required: true, options: ['us-east-1', 'us-west-2', 'eu-west-1'] },
    ],
    actions: ['Upsert', 'Query', 'Delete', 'Fetch'],
    tools: ['vectors', 'indexes', 'namespaces'],
    resources: ['Indexes', 'Collections'],
    rateLimits: { requests: 1000, period: 'minute' },
  },
  {
    id: 'qdrant',
    name: 'Qdrant',
    description: 'Open-source vector search engine with high performance.',
    logo: 'https://qdrant.github.io/qdrant/landing/content/images/qdrant_logo.svg',
    category: 'databases',
    status: 'connected',
    lastSync: new Date(Date.now() - 1000 * 60 * 10),
    version: '1.7.0',
    tags: ['Database', 'Vector', 'Open Source'],
    authType: 'api_key',
    configFields: [
      { key: 'url', label: 'URL', type: 'text', required: true, placeholder: 'http://localhost:6333' },
      { key: 'api_key', label: 'API Key', type: 'password', required: false },
    ],
    actions: ['Upsert', 'Search', 'Delete', 'Update'],
    tools: ['collections', 'points', 'payload'],
    resources: ['Collections', 'Snapshots'],
    rateLimits: { requests: 10000, period: 'minute' },
  },

  // Cloud
  {
    id: 'aws',
    name: 'AWS',
    description: 'Amazon Web Services integration for cloud infrastructure.',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/9/93/Amazon_Web_Services_Logo_and_wordmark.svg',
    category: 'cloud',
    status: 'available',
    version: '3.0.0',
    tags: ['Cloud', 'AWS', 'Infrastructure'],
    authType: 'basic',
    configFields: [
      { key: 'access_key', label: 'Access Key', type: 'text', required: true },
      { key: 'secret_key', label: 'Secret Key', type: 'password', required: true },
      { key: 'region', label: 'Region', type: 'select', required: true, options: ['us-east-1', 'us-west-2', 'eu-west-1', 'ap-southeast-1'] },
    ],
    actions: ['EC2', 'S3', 'Lambda', 'DynamoDB'],
    tools: ['compute', 'storage', 'serverless', 'database'],
    resources: ['Instances', 'Buckets', 'Functions'],
    rateLimits: { requests: 10000, period: 'second' },
  },
  {
    id: 'vercel',
    name: 'Vercel',
    description: 'Deploy and manage Next.js and other frontend applications.',
    logo: 'https://assets.vercel.com/image/upload/v1588805858/repositories/vercel/logo.png',
    category: 'cloud',
    status: 'available',
    version: '2.5.0',
    tags: ['Cloud', 'Hosting', 'Next.js'],
    authType: 'bearer',
    configFields: [
      { key: 'token', label: 'API Token', type: 'password', required: true },
    ],
    actions: ['Deploy', 'Preview', 'Monitor'],
    tools: ['projects', 'deployments', 'domains'],
    resources: ['Projects', 'Deployments'],
    rateLimits: { requests: 6000, period: 'hour' },
  },

  // Storage
  {
    id: 'aws-s3',
    name: 'AWS S3',
    description: 'Object storage for files, backups, and media assets.',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/b/bc/Amazon-S3-Logo.svg',
    category: 'storage',
    status: 'available',
    version: '1.5.0',
    tags: ['Storage', 'S3', 'Files'],
    authType: 'basic',
    configFields: [
      { key: 'access_key', label: 'Access Key', type: 'text', required: true },
      { key: 'secret_key', label: 'Secret Key', type: 'password', required: true },
      { key: 'bucket', label: 'Bucket Name', type: 'text', required: true },
      { key: 'region', label: 'Region', type: 'select', required: true, options: ['us-east-1', 'us-west-2', 'eu-west-1'] },
    ],
    actions: ['Upload', 'Download', 'List', 'Delete'],
    tools: ['objects', 'buckets', 'presigned_urls'],
    resources: ['Buckets', 'Objects'],
    rateLimits: { requests: 5500, period: 'second' },
  },
  {
    id: 'cloudflare-r2',
    name: 'Cloudflare R2',
    description: 'S3-compatible object storage without egress fees.',
    logo: 'https://www.cloudflare.com/img/cf-facebook-card.png',
    category: 'storage',
    status: 'needs_setup',
    version: '1.0.0',
    tags: ['Storage', 'R2', 'CDN'],
    authType: 'basic',
    configFields: [
      { key: 'account_id', label: 'Account ID', type: 'text', required: true },
      { key: 'access_key', label: 'Access Key', type: 'text', required: true },
      { key: 'secret_key', label: 'Secret Key', type: 'password', required: true },
      { key: 'bucket', label: 'Bucket Name', type: 'text', required: true },
    ],
    actions: ['Upload', 'Download', 'List', 'Delete'],
    tools: ['objects', 'buckets', 'presigned_urls'],
    resources: ['Buckets', 'Objects'],
    rateLimits: { requests: 10000, period: 'second' },
  },

  // Communication
  {
    id: 'discord',
    name: 'Discord',
    description: 'Send messages and manage Discord server interactions.',
    logo: 'https://assets-global.website-files.com/6257adef93867e50d84d30e2/636e0a6a49cf127bf92de1e2_icon_clyde_blurple_RGB.png',
    category: 'communication',
    status: 'available',
    version: '1.3.0',
    tags: ['Communication', 'Discord', 'Bot'],
    authType: 'bearer',
    configFields: [
      { key: 'bot_token', label: 'Bot Token', type: 'password', required: true },
    ],
    actions: ['Send Message', 'Manage Channel', 'React'],
    tools: ['channels', 'messages', 'webhooks'],
    resources: ['Servers', 'Channels', 'Users'],
    rateLimits: { requests: 50, period: 'second' },
  },
  {
    id: 'telegram',
    name: 'Telegram',
    description: 'Send messages and manage Telegram bot interactions.',
    logo: 'https://telegram.org/img/t_logo.png',
    category: 'communication',
    status: 'available',
    version: '1.2.0',
    tags: ['Communication', 'Telegram', 'Bot'],
    authType: 'api_key',
    configFields: [
      { key: 'bot_token', label: 'Bot Token', type: 'password', required: true },
    ],
    actions: ['Send Message', 'Send Photo', 'Create Group'],
    tools: ['sendMessage', 'sendPhoto', 'getUpdates'],
    resources: ['Chats', 'Users', 'Groups'],
    rateLimits: { requests: 30, period: 'second' },
  },

  // Productivity
  {
    id: 'notion',
    name: 'Notion',
    description: 'Integrate with Notion for notes, docs, and project management.',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png',
    category: 'productivity',
    status: 'available',
    version: '2.0.0',
    tags: ['Productivity', 'Notes', 'Docs'],
    authType: 'oauth',
    configFields: [
      { key: 'api_key', label: 'API Key', type: 'password', required: true },
    ],
    actions: ['Query Database', 'Create Page', 'Update Page'],
    tools: ['pages', 'databases', 'blocks'],
    resources: ['Pages', 'Databases', 'Users'],
    rateLimits: { requests: 3, period: 'second' },
  },
  {
    id: 'linear',
    name: 'Linear',
    description: 'Issue tracking and project management for software teams.',
    logo: 'https://linear.app/cdn-cgi/imagedelivery/fO02fVwohEs9s9UHFwon6A/6ccf9d05-1c7c-4f0f-9a2d-4f4d6e8e8e8e',
    category: 'productivity',
    status: 'available',
    version: '1.5.0',
    tags: ['Productivity', 'Issues', 'Project'],
    authType: 'api_key',
    configFields: [
      { key: 'api_key', label: 'API Key', type: 'password', required: true },
      { key: 'team_id', label: 'Team ID', type: 'text', required: false },
    ],
    actions: ['Create Issue', 'Update Issue', 'List Projects'],
    tools: ['issues', 'projects', 'teams'],
    resources: ['Issues', 'Projects', 'Teams'],
    rateLimits: { requests: 100, period: 'minute' },
  },

  // Finance
  {
    id: 'stripe',
    name: 'Stripe',
    description: 'Payment processing and subscription management.',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/b/ba/Stripe_Logo%2C_revised_2016.svg',
    category: 'finance',
    status: 'available',
    version: '3.0.0',
    tags: ['Finance', 'Payments', 'Subscriptions'],
    authType: 'bearer',
    configFields: [
      { key: 'secret_key', label: 'Secret Key', type: 'password', required: true },
      { key: 'webhook_secret', label: 'Webhook Secret', type: 'password', required: false },
    ],
    actions: ['Create Payment', 'Create Subscription', 'Refund'],
    tools: ['payments', 'subscriptions', 'customers'],
    resources: ['Payments', 'Subscriptions', 'Invoices'],
    rateLimits: { requests: 100, period: 'second' },
  },

  // Search
  {
    id: 'algolia',
    name: 'Algolia',
    description: 'Search and discovery platform for instant, relevant results.',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/b/b2/Algolia_logo.svg',
    category: 'search',
    status: 'available',
    version: '2.0.0',
    tags: ['Search', 'Discovery', 'AI'],
    authType: 'api_key',
    configFields: [
      { key: 'app_id', label: 'App ID', type: 'text', required: true },
      { key: 'api_key', label: 'API Key', type: 'password', required: true },
    ],
    actions: ['Search', 'Index', 'Configure'],
    tools: ['search', 'indexing', 'analytics'],
    resources: ['Indices', 'Rules', 'Synonyms'],
    rateLimits: { requests: 10000, period: 'minute' },
  },
  {
    id: 'typesense',
    name: 'Typesense',
    description: 'Fast, open-source search engine for building delightful search.',
    logo: 'https://typesense.org/typesense-cloud/img/typesense-logo.svg',
    category: 'search',
    status: 'available',
    version: '1.5.0',
    tags: ['Search', 'Open Source', 'Fast'],
    authType: 'api_key',
    configFields: [
      { key: 'url', label: 'URL', type: 'text', required: true },
      { key: 'api_key', label: 'API Key', type: 'password', required: true },
    ],
    actions: ['Search', 'Index', 'Delete'],
    tools: ['documents', 'collections', 'aliases'],
    resources: ['Collections', 'Documents'],
    rateLimits: { requests: 1000, period: 'second' },
  },

  // Developer Tools
  {
    id: 'datadog',
    name: 'Datadog',
    description: 'Monitor application performance and infrastructure.',
    logo: 'https://imgix.datadoghq.com/img/about/presskit/logo-v/dd_vertical_purple.png',
    category: 'developer_tools',
    status: 'available',
    version: '2.0.0',
    tags: ['Monitoring', 'APM', 'Logs'],
    authType: 'api_key',
    configFields: [
      { key: 'api_key', label: 'API Key', type: 'password', required: true },
      { key: 'app_key', label: 'App Key', type: 'password', required: true },
    ],
    actions: ['Query Metrics', 'Create Dashboard', 'Send Logs'],
    tools: ['metrics', 'logs', 'traces', 'dashboards'],
    resources: ['Metrics', 'Logs', 'Traces'],
    rateLimits: { requests: 1000, period: 'minute' },
  },
  {
    id: 'sentry',
    name: 'Sentry',
    description: 'Error tracking and performance monitoring for applications.',
    logo: 'https://sentry-brand.storage.googleapis.com/sentry-logo-black.png',
    category: 'developer_tools',
    status: 'available',
    version: '2.5.0',
    tags: ['Monitoring', 'Errors', 'APM'],
    authType: 'bearer',
    configFields: [
      { key: 'dsn', label: 'DSN', type: 'text', required: true, placeholder: 'https://...' },
      { key: 'auth_token', label: 'Auth Token', type: 'password', required: false },
    ],
    actions: ['Track Error', 'Track Event', 'Query Issues'],
    tools: ['errors', 'performance', 'releases'],
    resources: ['Projects', 'Issues', 'Events'],
    rateLimits: { requests: 1000, period: 'second' },
  },

  // Custom
  {
    id: 'custom-rest',
    name: 'Custom REST API',
    description: 'Connect to any REST API with custom authentication and endpoints.',
    logo: 'https://cdn-icons-png.flaticon.com/512/1041/1041916.png',
    category: 'custom',
    status: 'available',
    version: '1.0.0',
    tags: ['Custom', 'REST', 'API'],
    authType: 'custom',
    configFields: [
      { key: 'base_url', label: 'Base URL', type: 'text', required: true },
      { key: 'auth_type', label: 'Auth Type', type: 'select', required: true, options: ['none', 'api_key', 'bearer', 'basic'] },
      { key: 'api_key', label: 'API Key', type: 'password', required: false },
      { key: 'headers', label: 'Custom Headers (JSON)', type: 'text', required: false },
    ],
    actions: ['GET', 'POST', 'PUT', 'DELETE'],
    tools: ['custom_requests'],
    resources: ['Custom Endpoints'],
    rateLimits: { requests: 100, period: 'second' },
  },
];

export const categories: CategoryInfo[] = [
  { id: 'all', label: 'All Integrations', icon: 'apps' },
  { id: 'ai_models', label: 'AI Models', icon: 'psychology' },
  { id: 'mcp_servers', label: 'MCP Servers', icon: 'account_tree' },
  { id: 'databases', label: 'Databases', icon: 'storage' },
  { id: 'cloud', label: 'Cloud', icon: 'cloud' },
  { id: 'storage', label: 'Storage', icon: 'folder' },
  { id: 'communication', label: 'Communication', icon: 'chat' },
  { id: 'productivity', label: 'Productivity', icon: 'task_alt' },
  { id: 'finance', label: 'Finance', icon: 'account_balance' },
  { id: 'search', label: 'Search', icon: 'search' },
  { id: 'developer_tools', label: 'Developer Tools', icon: 'code' },
  { id: 'custom', label: 'Custom', icon: 'settings' },
];

export const mockLogs: { id: string; timestamp: Date; level: 'info' | 'warning' | 'error'; message: string; details?: string }[] = [
  { id: '1', timestamp: new Date(Date.now() - 1000 * 60 * 5), level: 'info', message: 'Connection established', details: 'Successfully connected to API endpoint' },
  { id: '2', timestamp: new Date(Date.now() - 1000 * 60 * 10), level: 'info', message: 'Data synced', details: 'Synced 150 records' },
  { id: '3', timestamp: new Date(Date.now() - 1000 * 60 * 30), level: 'warning', message: 'Rate limit approaching', details: '80% of hourly limit used' },
  { id: '4', timestamp: new Date(Date.now() - 1000 * 60 * 60), level: 'error', message: 'Authentication failed', details: 'Invalid API key provided' },
  { id: '5', timestamp: new Date(Date.now() - 1000 * 60 * 120), level: 'info', message: 'Configuration updated', details: 'Endpoint URL changed' },
];